package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Complements generated by hbm2java
 */
public class Complements  implements java.io.Serializable {


     private Integer idComplement;
     private String name;
     private Set relRestCmps = new HashSet(0);

    public Complements() {
    }

	
    public Complements(String name) {
        this.name = name;
    }
    public Complements(String name, Set relRestCmps) {
       this.name = name;
       this.relRestCmps = relRestCmps;
    }
   
    public Integer getIdComplement() {
        return this.idComplement;
    }
    
    public void setIdComplement(Integer idComplement) {
        this.idComplement = idComplement;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRelRestCmps() {
        return this.relRestCmps;
    }
    
    public void setRelRestCmps(Set relRestCmps) {
        this.relRestCmps = relRestCmps;
    }




}


