package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Drinks generated by hbm2java
 */
public class Drinks  implements java.io.Serializable {


     private Integer idDrink;
     private String name;
     private Set relRestDrks = new HashSet(0);

    public Drinks() {
    }

	
    public Drinks(String name) {
        this.name = name;
    }
    public Drinks(String name, Set relRestDrks) {
       this.name = name;
       this.relRestDrks = relRestDrks;
    }
   
    public Integer getIdDrink() {
        return this.idDrink;
    }
    
    public void setIdDrink(Integer idDrink) {
        this.idDrink = idDrink;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRelRestDrks() {
        return this.relRestDrks;
    }
    
    public void setRelRestDrks(Set relRestDrks) {
        this.relRestDrks = relRestDrks;
    }




}


