package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idOrder;
     private Tables tables;
     private byte sended;
     private Set productsbyorders = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Tables tables, byte sended) {
        this.tables = tables;
        this.sended = sended;
    }
    public Orders(Tables tables, byte sended, Set productsbyorders) {
       this.tables = tables;
       this.sended = sended;
       this.productsbyorders = productsbyorders;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public Tables getTables() {
        return this.tables;
    }
    
    public void setTables(Tables tables) {
        this.tables = tables;
    }
    public byte getSended() {
        return this.sended;
    }
    
    public void setSended(byte sended) {
        this.sended = sended;
    }
    public Set getProductsbyorders() {
        return this.productsbyorders;
    }
    
    public void setProductsbyorders(Set productsbyorders) {
        this.productsbyorders = productsbyorders;
    }




}


