package Entities;
// Generated 12-nov-2016 9:38:35 by Hibernate Tools 4.3.1



/**
 * Productsbyorder generated by hbm2java
 */
public class Productsbyorder  implements java.io.Serializable {


     private Integer idProductsByOrder;
     private Orders orders;
     private String productType;
     private int productId;
     private int quantity;

    public Productsbyorder() {
    }

    public Productsbyorder(Orders orders, String productType, int productId, int quantity) {
       this.orders = orders;
       this.productType = productType;
       this.productId = productId;
       this.quantity = quantity;
    }
   
    public Integer getIdProductsByOrder() {
        return this.idProductsByOrder;
    }
    
    public void setIdProductsByOrder(Integer idProductsByOrder) {
        this.idProductsByOrder = idProductsByOrder;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


