package Entities;
// Generated 12-nov-2016 9:38:35 by Hibernate Tools 4.3.1



/**
 * RelRestCmp generated by hbm2java
 */
public class RelRestCmp  implements java.io.Serializable {


     private Integer idRelRestCmp;
     private Complements complements;
     private Restaurants restaurants;
     private Integer stock;

    public RelRestCmp() {
    }

	
    public RelRestCmp(Complements complements, Restaurants restaurants) {
        this.complements = complements;
        this.restaurants = restaurants;
    }
    public RelRestCmp(Complements complements, Restaurants restaurants, Integer stock) {
       this.complements = complements;
       this.restaurants = restaurants;
       this.stock = stock;
    }
   
    public Integer getIdRelRestCmp() {
        return this.idRelRestCmp;
    }
    
    public void setIdRelRestCmp(Integer idRelRestCmp) {
        this.idRelRestCmp = idRelRestCmp;
    }
    public Complements getComplements() {
        return this.complements;
    }
    
    public void setComplements(Complements complements) {
        this.complements = complements;
    }
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }




}


