package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1



/**
 * RelRestDrk generated by hbm2java
 */
public class RelRestDrk  implements java.io.Serializable {


     private Integer idRelRestDrk;
     private Drinks drinks;
     private Restaurants restaurants;
     private Integer stock;

    public RelRestDrk() {
    }

	
    public RelRestDrk(Drinks drinks, Restaurants restaurants) {
        this.drinks = drinks;
        this.restaurants = restaurants;
    }
    public RelRestDrk(Drinks drinks, Restaurants restaurants, Integer stock) {
       this.drinks = drinks;
       this.restaurants = restaurants;
       this.stock = stock;
    }
   
    public Integer getIdRelRestDrk() {
        return this.idRelRestDrk;
    }
    
    public void setIdRelRestDrk(Integer idRelRestDrk) {
        this.idRelRestDrk = idRelRestDrk;
    }
    public Drinks getDrinks() {
        return this.drinks;
    }
    
    public void setDrinks(Drinks drinks) {
        this.drinks = drinks;
    }
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }




}


