package Entities;
// Generated 12-nov-2016 9:38:35 by Hibernate Tools 4.3.1



/**
 * RelRestMak generated by hbm2java
 */
public class RelRestMak  implements java.io.Serializable {


     private Integer idRelRestMak;
     private Makis makis;
     private Restaurants restaurants;
     private Integer stock;

    public RelRestMak() {
    }

	
    public RelRestMak(Makis makis, Restaurants restaurants) {
        this.makis = makis;
        this.restaurants = restaurants;
    }
    public RelRestMak(Makis makis, Restaurants restaurants, Integer stock) {
       this.makis = makis;
       this.restaurants = restaurants;
       this.stock = stock;
    }
   
    public Integer getIdRelRestMak() {
        return this.idRelRestMak;
    }
    
    public void setIdRelRestMak(Integer idRelRestMak) {
        this.idRelRestMak = idRelRestMak;
    }
    public Makis getMakis() {
        return this.makis;
    }
    
    public void setMakis(Makis makis) {
        this.makis = makis;
    }
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }




}


