package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurants generated by hbm2java
 */
public class Restaurants  implements java.io.Serializable {


     private Integer idRestaurant;
     private String name;
     private String imgSource;
     private Set relRestDrks = new HashSet(0);
     private Set tableses = new HashSet(0);
     private Set waiters = new HashSet(0);
     private Set relRestMaks = new HashSet(0);
     private Set relRestCmps = new HashSet(0);

    public Restaurants() {
    }

	
    public Restaurants(String name, String imgSource) {
        this.name = name;
        this.imgSource = imgSource;
    }
    public Restaurants(String name, String imgSource, Set relRestDrks, Set tableses, Set waiters, Set relRestMaks, Set relRestCmps) {
       this.name = name;
       this.imgSource = imgSource;
       this.relRestDrks = relRestDrks;
       this.tableses = tableses;
       this.waiters = waiters;
       this.relRestMaks = relRestMaks;
       this.relRestCmps = relRestCmps;
    }
   
    public Integer getIdRestaurant() {
        return this.idRestaurant;
    }
    
    public void setIdRestaurant(Integer idRestaurant) {
        this.idRestaurant = idRestaurant;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImgSource() {
        return this.imgSource;
    }
    
    public void setImgSource(String imgSource) {
        this.imgSource = imgSource;
    }
    public Set getRelRestDrks() {
        return this.relRestDrks;
    }
    
    public void setRelRestDrks(Set relRestDrks) {
        this.relRestDrks = relRestDrks;
    }
    public Set getTableses() {
        return this.tableses;
    }
    
    public void setTableses(Set tableses) {
        this.tableses = tableses;
    }
    public Set getWaiters() {
        return this.waiters;
    }
    
    public void setWaiters(Set waiters) {
        this.waiters = waiters;
    }
    public Set getRelRestMaks() {
        return this.relRestMaks;
    }
    
    public void setRelRestMaks(Set relRestMaks) {
        this.relRestMaks = relRestMaks;
    }
    public Set getRelRestCmps() {
        return this.relRestCmps;
    }
    
    public void setRelRestCmps(Set relRestCmps) {
        this.relRestCmps = relRestCmps;
    }




}


