package Entities;
// Generated 12-nov-2016 9:38:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tables generated by hbm2java
 */
public class Tables  implements java.io.Serializable {


     private Integer idTable;
     private Restaurants restaurants;
     private Typetables typetables;
     private Waiter waiter;
     private String username;
     private String password;
     private boolean attended;
     private Set orderses = new HashSet(0);

    public Tables() {
    }

	
    public Tables(Restaurants restaurants, Typetables typetables, Waiter waiter, String username, String password, boolean attended) {
        this.restaurants = restaurants;
        this.typetables = typetables;
        this.waiter = waiter;
        this.username = username;
        this.password = password;
        this.attended = attended;
    }
    public Tables(Restaurants restaurants, Typetables typetables, Waiter waiter, String username, String password, boolean attended, Set orderses) {
       this.restaurants = restaurants;
       this.typetables = typetables;
       this.waiter = waiter;
       this.username = username;
       this.password = password;
       this.attended = attended;
       this.orderses = orderses;
    }
   
    public Integer getIdTable() {
        return this.idTable;
    }
    
    public void setIdTable(Integer idTable) {
        this.idTable = idTable;
    }
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }
    public Typetables getTypetables() {
        return this.typetables;
    }
    
    public void setTypetables(Typetables typetables) {
        this.typetables = typetables;
    }
    public Waiter getWaiter() {
        return this.waiter;
    }
    
    public void setWaiter(Waiter waiter) {
        this.waiter = waiter;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAttended() {
        return this.attended;
    }
    
    public void setAttended(boolean attended) {
        this.attended = attended;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


