package Entities;
// Generated 20-nov-2016 13:40:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typetables generated by hbm2java
 */
public class Typetables  implements java.io.Serializable {


     private Integer idTypeTable;
     private String name;
     private Set tableses = new HashSet(0);

    public Typetables() {
    }

	
    public Typetables(String name) {
        this.name = name;
    }
    public Typetables(String name, Set tableses) {
       this.name = name;
       this.tableses = tableses;
    }
   
    public Integer getIdTypeTable() {
        return this.idTypeTable;
    }
    
    public void setIdTypeTable(Integer idTypeTable) {
        this.idTypeTable = idTypeTable;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTableses() {
        return this.tableses;
    }
    
    public void setTableses(Set tableses) {
        this.tableses = tableses;
    }




}


