package Entities;
// Generated 12-nov-2016 9:38:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Waiter generated by hbm2java
 */
public class Waiter  implements java.io.Serializable {


     private Integer idWaiter;
     private Restaurants restaurants;
     private String name;
     private String srcImg;
     private Set tableses = new HashSet(0);

    public Waiter() {
    }

	
    public Waiter(Restaurants restaurants, String name, String srcImg) {
        this.restaurants = restaurants;
        this.name = name;
        this.srcImg = srcImg;
    }
    public Waiter(Restaurants restaurants, String name, String srcImg, Set tableses) {
       this.restaurants = restaurants;
       this.name = name;
       this.srcImg = srcImg;
       this.tableses = tableses;
    }
   
    public Integer getIdWaiter() {
        return this.idWaiter;
    }
    
    public void setIdWaiter(Integer idWaiter) {
        this.idWaiter = idWaiter;
    }
    public Restaurants getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Restaurants restaurants) {
        this.restaurants = restaurants;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSrcImg() {
        return this.srcImg;
    }
    
    public void setSrcImg(String srcImg) {
        this.srcImg = srcImg;
    }
    public Set getTableses() {
        return this.tableses;
    }
    
    public void setTableses(Set tableses) {
        this.tableses = tableses;
    }




}


